from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.inp_score_p1 = QtWidgets.QLineEdit(self.groupBox)
        self.inp_score_p1.setObjectName("inp_score_p1")
        self.verticalLayout_2.addWidget(self.inp_score_p1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.inp_score_p2 = QtWidgets.QLineEdit(self.groupBox)
        self.inp_score_p2.setObjectName("inp_score_p2")
        self.verticalLayout_2.addWidget(self.inp_score_p2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.inp_name_p1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.inp_name_p1.setObjectName("inp_name_p1")
        self.verticalLayout_3.addWidget(self.inp_name_p1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.inp_name_p2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.inp_name_p2.setObjectName("inp_name_p2")
        self.verticalLayout_3.addWidget(self.inp_name_p2)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_new_game = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_new_game.setObjectName("btn_new_game")
        self.verticalLayout_5.addWidget(self.btn_new_game)
        self.btn_options = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_options.setObjectName("btn_options")
        self.verticalLayout_5.addWidget(self.btn_options)
        self.btn_exit = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_5.addWidget(self.btn_exit)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.img_enemy_cards = QtWidgets.QLabel(self.frame_2)
        self.img_enemy_cards.setText("")
        self.img_enemy_cards.setPixmap(QtGui.QPixmap("./assets/enemy_card.png"))
        self.img_enemy_cards.setAlignment(QtCore.Qt.AlignCenter)
        self.img_enemy_cards.setObjectName("img_enemy_cards")
        self.verticalLayout_4.addWidget(self.img_enemy_cards)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lbl_enemy_attack = QtWidgets.QPushButton(self.groupBox_4)
        self.lbl_enemy_attack.setObjectName("lbl_enemy_attack")
        self.horizontalLayout_3.addWidget(self.lbl_enemy_attack)
        self.lbl_enemy_defense = QtWidgets.QPushButton(self.groupBox_4)
        self.lbl_enemy_defense.setObjectName("lbl_enemy_defense")
        self.horizontalLayout_3.addWidget(self.lbl_enemy_defense)
        self.lbl_enemy_element = QtWidgets.QPushButton(self.groupBox_4)
        self.lbl_enemy_element.setObjectName("lbl_enemy_element")
        self.horizontalLayout_3.addWidget(self.lbl_enemy_element)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("./assets/rect.png"))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lbl_score = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lbl_score.setFont(font)
        self.lbl_score.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_score.setObjectName("lbl_score")
        self.horizontalLayout_2.addWidget(self.lbl_score)
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("./assets/rect.png"))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.lbl_my_attack = QtWidgets.QPushButton(self.groupBox_5)
        self.lbl_my_attack.setObjectName("lbl_my_attack")
        self.horizontalLayout_4.addWidget(self.lbl_my_attack)
        self.lbl_my_defense = QtWidgets.QPushButton(self.groupBox_5)
        self.lbl_my_defense.setObjectName("lbl_my_defense")
        self.horizontalLayout_4.addWidget(self.lbl_my_defense)
        self.lbl_my_element = QtWidgets.QPushButton(self.groupBox_5)
        self.lbl_my_element.setObjectName("lbl_my_element")
        self.horizontalLayout_4.addWidget(self.lbl_my_element)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.card_1 = QtWidgets.QLabel(self.groupBox_7)
        self.card_1.setText("")
        self.card_1.setPixmap(QtGui.QPixmap("./assets/card.png"))
        self.card_1.setObjectName("card_1")
        self.horizontalLayout_5.addWidget(self.card_1)
        self.card_2 = QtWidgets.QLabel(self.groupBox_7)
        self.card_2.setText("")
        self.card_2.setPixmap(QtGui.QPixmap("./assets/card.png"))
        self.card_2.setObjectName("card_2")
        self.horizontalLayout_5.addWidget(self.card_2)
        self.card_3 = QtWidgets.QLabel(self.groupBox_7)
        self.card_3.setText("")
        self.card_3.setPixmap(QtGui.QPixmap("./assets/card.png"))
        self.card_3.setObjectName("card_3")
        self.horizontalLayout_5.addWidget(self.card_3)
        self.card_4 = QtWidgets.QLabel(self.groupBox_7)
        self.card_4.setText("")
        self.card_4.setPixmap(QtGui.QPixmap("./assets/card.png"))
        self.card_4.setObjectName("card_4")
        self.horizontalLayout_5.addWidget(self.card_4)
        self.card_5 = QtWidgets.QLabel(self.groupBox_7)
        self.card_5.setText("")
        self.card_5.setPixmap(QtGui.QPixmap("./assets/card.png"))
        self.card_5.setObjectName("card_5")
        self.horizontalLayout_5.addWidget(self.card_5)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(265, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_New_Game = QtWidgets.QAction(MainWindow)
        self.action_New_Game.setObjectName("action_New_Game")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.menu_File.addAction(self.action_New_Game)
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())

        """ edit """
        self.btn_exit.clicked.connect(lambda: MainWindow.close())
        self.btn_new_game.clicked.connect(self.new_game)
        self.card_1.clicked.connect(self.print_)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Score"))
        self.label.setText(_translate("MainWindow", "Score"))
        self.label_2.setText(_translate("MainWindow", "Player 1"))
        self.label_3.setText(_translate("MainWindow", "Player 2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Players"))
        self.label_4.setText(_translate("MainWindow", "Players Name"))
        self.label_6.setText(_translate("MainWindow", "Player 1"))
        self.label_5.setText(_translate("MainWindow", "Player 2"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Menu"))
        self.btn_new_game.setText(_translate("MainWindow", "New Game"))
        self.btn_options.setText(_translate("MainWindow", "Options"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
        self.lbl_enemy_attack.setText(_translate("MainWindow", "Attack: 0"))
        self.lbl_enemy_defense.setText(_translate("MainWindow", "Defense: 0"))
        self.lbl_enemy_element.setText(_translate("MainWindow", "Element: 0"))
        self.lbl_score.setText(_translate("MainWindow", "9 x 8"))
        self.lbl_my_attack.setText(_translate("MainWindow", "Attack: 0"))
        self.lbl_my_defense.setText(_translate("MainWindow", "Defense: 0"))
        self.lbl_my_element.setText(_translate("MainWindow", "Element: 0"))
        self.pushButton.setText(_translate("MainWindow", "PLAY"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.action_New_Game.setText(_translate("MainWindow", "&New Game"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))

    def new_game(self):
        pass

    def generate_deck(self):
        pass

    def print_(self):
        print(1)
class GuiGame:
    def __init__(self, player1, player2):
        self.player1 = player1
        self.player2 = player2
        self.played_cards_1 = [False, False, False, False, False]
        self.played_cards_2 = [False, False, False, False, False]
        self.score_p1 = 0
        self.score_p2 = 0
        self.deck_1 = self.player1.get_deck()
        self.deck_2 = self.player2.get_deck()
        self.play = True
        self.winner = ''

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
