# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Game.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import random
import pprint
import time
import glob

from PyQt5 import QtCore, QtGui, QtWidgets
from cards import *
from style import *
from termcolor import cprint

from ui import Options

print_error = lambda x: cprint(x, 'red', attrs=['bold'])
print_grey_on_yellow2 = lambda x: cprint(x, 'grey', 'on_yellow', end=' ')
print_grey_on_yellow = lambda x: cprint(x, 'grey', 'on_yellow')
print_yellow_on_grey2 = lambda x: cprint(x, 'yellow', 'on_grey', end=' ')
print_yellow_on_grey = lambda x: cprint(x, 'yellow', 'on_grey')
print_cyan = lambda x: cprint(x, 'cyan', attrs=['bold'])
print_warning2 = lambda x: cprint(x, 'yellow', end=' ')
print_warning = lambda x: cprint(x, 'yellow')
print_info2 = lambda x: cprint(x, 'blue', end=' ')
print_info = lambda x: cprint(x, 'blue')
print_green2 = lambda x: cprint(x, 'green', end=' ')
print_green = lambda x: cprint(x, 'green')
print_win = lambda x: cprint(x, 'yellow')


class Ui_MainWindow(object):
    def __init__(self):
        self.deck_p1 = []
        self.deck_p2 = []

        self.card_p1 = {}
        self.card_p2 = {}

        self.my_attack = 'Attack: ???'
        self.my_defense = 'Defense: ???'
        self.my_element = 'Element: ???'

        self.en_attack = ''
        self.en_defense = ''
        self.en_element = ''

        self.total_p1 = 0
        self.total_p2 = 0

        self.score_p1 = 0
        self.score_p2 = 0

        self.played_cards = 5

        # cards from folder
        self.all_cards = []

        self.deck_p1_new = []
        self.deck_p2_new = []

        self.deck_p1_new_dict = {}
        self.deck_p2_new_dict = {}

        self.deck_p1_picked = {}
        self.deck_p2_picked = {}

        self.total_p1_new = 0
        self.total_p2_new = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(893, 631)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.inp_score_p1 = QtWidgets.QLineEdit(self.groupBox)
        self.inp_score_p1.setObjectName("inp_score_p1")
        self.verticalLayout_2.addWidget(self.inp_score_p1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.inp_score_p2 = QtWidgets.QLineEdit(self.groupBox)
        self.inp_score_p2.setObjectName("inp_score_p2")
        self.verticalLayout_2.addWidget(self.inp_score_p2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.inp_name_p1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.inp_name_p1.setObjectName("inp_name_p1")
        self.verticalLayout_3.addWidget(self.inp_name_p1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.inp_name_p2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.inp_name_p2.setObjectName("inp_name_p2")
        self.verticalLayout_3.addWidget(self.inp_name_p2)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_new_game = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_new_game.setObjectName("btn_new_game")
        self.verticalLayout_5.addWidget(self.btn_new_game)
        self.btn_options = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_options.setObjectName("btn_options")
        self.verticalLayout_5.addWidget(self.btn_options)
        self.btn_exit = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout_5.addWidget(self.btn_exit)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.img_enemy_cards = QtWidgets.QLabel(self.frame_2)
        self.img_enemy_cards.setText("")
        self.img_enemy_cards.setPixmap(QtGui.QPixmap("./assets/enemy_card5.png"))
        self.img_enemy_cards.setAlignment(QtCore.Qt.AlignCenter)
        self.img_enemy_cards.setObjectName("img_enemy_cards")
        self.verticalLayout_4.addWidget(self.img_enemy_cards)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lbl_enemy_attack = QtWidgets.QPushButton(self.groupBox_4)
        self.lbl_enemy_attack.setObjectName("lbl_enemy_attack")
        self.horizontalLayout_3.addWidget(self.lbl_enemy_attack)
        self.lbl_enemy_defense = QtWidgets.QPushButton(self.groupBox_4)
        self.lbl_enemy_defense.setObjectName("lbl_enemy_defense")
        self.horizontalLayout_3.addWidget(self.lbl_enemy_defense)
        self.lbl_enemy_element = QtWidgets.QPushButton(self.groupBox_4)
        self.lbl_enemy_element.setObjectName("lbl_enemy_element")
        self.horizontalLayout_3.addWidget(self.lbl_enemy_element)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("./assets/rect.png"))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lbl_score = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lbl_score.setFont(font)
        self.lbl_score.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_score.setObjectName("lbl_score")
        self.horizontalLayout_2.addWidget(self.lbl_score)
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("./assets/rect.png"))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.verticalLayout_4.addWidget(self.groupBox_6)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)

        self.lbl_my_attack = QtWidgets.QPushButton(self.groupBox_5)
        self.lbl_my_attack.setObjectName("lbl_my_attack")
        self.horizontalLayout_4.addWidget(self.lbl_my_attack)

        self.lbl_my_defense = QtWidgets.QPushButton(self.groupBox_5)
        self.lbl_my_defense.setObjectName("lbl_my_defense")
        self.horizontalLayout_4.addWidget(self.lbl_my_defense)

        self.lbl_my_element = QtWidgets.QPushButton(self.groupBox_5)
        self.lbl_my_element.setObjectName("lbl_my_element")
        self.horizontalLayout_4.addWidget(self.lbl_my_element)

        self.lbl_my_result = QtWidgets.QPushButton(self.groupBox_5)
        self.lbl_my_result.setObjectName("lbl_my_result")
        self.horizontalLayout_4.addWidget(self.lbl_my_result)

        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.card_1 = QtWidgets.QPushButton(self.groupBox_7)
        self.card_1.setStyleSheet("border: 0;")
        self.card_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./assets/card.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.card_1.setIcon(icon)
        self.card_1.setIconSize(QtCore.QSize(120, 160))
        self.card_1.setObjectName("card_1")
        self.horizontalLayout_5.addWidget(self.card_1)
        self.card_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.card_2.setStyleSheet("border: 0;")
        self.card_2.setText("")
        self.card_2.setIcon(icon)
        self.card_2.setIconSize(QtCore.QSize(120, 160))
        self.card_2.setObjectName("card_2")
        self.horizontalLayout_5.addWidget(self.card_2)
        self.card_3 = QtWidgets.QPushButton(self.groupBox_7)
        self.card_3.setStyleSheet("border: 0;")
        self.card_3.setText("")
        self.card_3.setIcon(icon)
        self.card_3.setIconSize(QtCore.QSize(120, 160))
        self.card_3.setObjectName("card_3")
        self.horizontalLayout_5.addWidget(self.card_3)
        self.card_4 = QtWidgets.QPushButton(self.groupBox_7)
        self.card_4.setStyleSheet("border: 0;")
        self.card_4.setText("")
        self.card_4.setIcon(icon)
        self.card_4.setIconSize(QtCore.QSize(120, 160))
        self.card_4.setObjectName("card_4")
        self.horizontalLayout_5.addWidget(self.card_4)
        self.card_5 = QtWidgets.QPushButton(self.groupBox_7)
        self.card_5.setStyleSheet("border: 0;")
        self.card_5.setText("")
        self.card_5.setIcon(icon)
        self.card_5.setIconSize(QtCore.QSize(120, 160))
        self.card_5.setObjectName("card_5")
        self.horizontalLayout_5.addWidget(self.card_5)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        spacerItem6 = QtWidgets.QSpacerItem(265, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 893, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_New_Game = QtWidgets.QAction(MainWindow)
        self.action_New_Game.setObjectName("action_New_Game")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.menu_File.addAction(self.action_New_Game)
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.label_2.setBuddy(self.inp_score_p1)
        self.label_3.setBuddy(self.inp_score_p2)
        self.label_6.setBuddy(self.inp_name_p1)
        self.label_5.setBuddy(self.inp_name_p2)

        """ style """
        self.pushButton.setStyleSheet(btn_primary)
        self.lbl_score.setStyleSheet(lbl_stats)
        self.inp_score_p1.setStyleSheet(lbl_player_score)
        self.inp_score_p2.setStyleSheet(lbl_player_score)

        self.inp_name_p1.setStyleSheet(lbl_player_score)
        self.inp_name_p2.setStyleSheet(lbl_player_score)

        self.lbl_enemy_element.setStyleSheet(lbl_stats)
        self.lbl_enemy_attack.setStyleSheet(lbl_stats)
        self.lbl_enemy_defense.setStyleSheet(lbl_stats)

        self.lbl_my_element.setStyleSheet(lbl_stats)
        self.lbl_my_attack.setStyleSheet(lbl_stats)
        self.lbl_my_defense.setStyleSheet(lbl_stats)
        self.lbl_my_result.setStyleSheet(lbl_stats)

        self.btn_new_game.setStyleSheet(btn_primary)
        self.btn_options.setStyleSheet(btn_primary)
        self.btn_exit.setStyleSheet(btn_primary)

        """ menu """
        self.btn_new_game.clicked.connect(self.new_game)
        self.action_New_Game.triggered.connect(self.new_game)
        self.btn_options.clicked.connect(self.w_options)
        self.btn_exit.clicked.connect(lambda : MainWindow.close())

        """ start """
        self.inp_name_p1.setText('Joana')
        self.inp_name_p2.setText('Gill')
        self.p1 = self.inp_name_p1.text()
        self.p2 = self.inp_name_p2.text()
        self.start(self.p1, self.p2)

        """ buttons """
        self.card_1.clicked.connect(lambda:self.pick(1))
        self.card_2.clicked.connect(lambda:self.pick(2))
        self.card_3.clicked.connect(lambda:self.pick(3))
        self.card_4.clicked.connect(lambda:self.pick(4))
        self.card_5.clicked.connect(lambda:self.pick(5))

        """ inputs, labels """
        self.inp_score_p1.setReadOnly(True)
        self.inp_score_p2.setReadOnly(True)
        self.inp_score_p1.setText('0')
        self.inp_score_p2.setText('0')
        self.lbl_score.setText('0 x 0')

        """ match """
        self.pushButton.clicked.connect(self.match)



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.inp_score_p1, self.inp_score_p2)
        MainWindow.setTabOrder(self.inp_score_p2, self.inp_name_p1)
        MainWindow.setTabOrder(self.inp_name_p1, self.inp_name_p2)
        MainWindow.setTabOrder(self.inp_name_p2, self.btn_new_game)
        MainWindow.setTabOrder(self.btn_new_game, self.btn_options)
        MainWindow.setTabOrder(self.btn_options, self.btn_exit)
        MainWindow.setTabOrder(self.btn_exit, self.lbl_enemy_attack)
        MainWindow.setTabOrder(self.lbl_enemy_attack, self.lbl_enemy_defense)
        MainWindow.setTabOrder(self.lbl_enemy_defense, self.lbl_enemy_element)
        MainWindow.setTabOrder(self.lbl_enemy_element, self.lbl_my_attack)
        MainWindow.setTabOrder(self.lbl_my_attack, self.lbl_my_defense)
        MainWindow.setTabOrder(self.lbl_my_defense, self.lbl_my_element)
        MainWindow.setTabOrder(self.lbl_my_element, self.card_1)
        MainWindow.setTabOrder(self.card_1, self.card_2)
        MainWindow.setTabOrder(self.card_2, self.card_3)
        MainWindow.setTabOrder(self.card_3, self.card_4)
        MainWindow.setTabOrder(self.card_4, self.card_5)
        MainWindow.setTabOrder(self.card_5, self.pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Score"))
        self.label.setText(_translate("MainWindow", "Score"))
        self.label_2.setText(_translate("MainWindow", "Player 1"))
        self.label_3.setText(_translate("MainWindow", "Player 2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Players"))
        self.label_4.setText(_translate("MainWindow", "Players Name"))
        self.label_6.setText(_translate("MainWindow", "Player 1"))
        self.label_5.setText(_translate("MainWindow", "Player 2"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Menu"))
        self.btn_new_game.setText(_translate("MainWindow", "New Game"))
        self.btn_options.setText(_translate("MainWindow", "Options"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
        self.lbl_enemy_attack.setText(_translate("MainWindow", "Attack: ???"))
        self.lbl_enemy_defense.setText(_translate("MainWindow", "Defense: ???"))
        self.lbl_enemy_element.setText(_translate("MainWindow", "Element: ???"))
        self.lbl_score.setText(_translate("MainWindow", "0 x 0"))
        self.lbl_my_attack.setText(_translate("MainWindow", self.my_attack))
        self.lbl_my_defense.setText(_translate("MainWindow", self.my_defense))
        self.lbl_my_element.setText(_translate("MainWindow", self.my_element))
        self.lbl_my_result.setText(_translate("MainWindow", f'Result: {str(self.total_p1)}'))
        self.pushButton.setText(_translate("MainWindow", "PLAY"))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.action_New_Game.setText(_translate("MainWindow", "&New Game"))
        self.action_Exit.setText(_translate("MainWindow", "&Exit"))

    def new_game(self):
        p1 = self.inp_name_p1.text()
        p2 = self.inp_name_p2.text()
        self.reset()
        self.start(p1, p2)

    def set_pick(self, p1):
        a = p1['attack']
        d = p1['defense']
        e = p1['element']
        self.lbl_my_attack.setText(a)
        self.lbl_my_defense.setText(d)
        self.lbl_my_element.setText(e)

    def pick(self, pick):
        if self.score_p1 == 3 or self.score_p2 == 3:
            self.reset()

        self.lbl_enemy_attack.setText("Attack: ???")
        self.lbl_enemy_defense.setText("Defense: ???")
        self.lbl_enemy_element.setText("Element: ???")

        self.card_p1 = self.deck_p1[pick - 1]
        self.card_p2 = self.deck_p2[pick - 1]

        p1_atk = self.card_p1['attack']
        p1_def = self.card_p1['defense']
        p1_elm = self.card_p1['element']

        p2_atk = self.card_p2['attack']
        p2_def = self.card_p2['defense']
        p2_elm = self.card_p2['element']

        self.my_attack = p1_atk
        self.my_defense = p1_def
        self.my_element = p1_elm

        self.en_attack = p2_atk
        self.en_defense = p2_def
        self.en_element = p2_elm

        self.lbl_my_attack.setText(str(f'Attack: {self.my_attack}'))
        self.lbl_my_defense.setText(str(f'Defense: {self.my_defense}'))
        self.lbl_my_element.setText(str(f'Element: {self.my_element}'))

        self.total_p1 = int(p1_atk) - int(p2_def)
        self.total_p2 = int(p2_atk) - int(p1_def)

        self.lbl_my_result.setText(str(f'Result: {self.total_p1}'))

        # new with images p1
        self.lbl_my_attack.setText(str(f'Attack: {self.deck_p1_new_dict[f"card{pick}"]["attack"]}'))
        self.lbl_my_defense.setText(str(f'Defense: {self.deck_p1_new_dict[f"card{pick}"]["defense"]}'))
        self.lbl_my_element.setText(str(f'Element: {self.deck_p1_new_dict[f"card{pick}"]["element"]}'))

        # sum of stats p1
        self.deck_p1_picked = self.deck_p1_new_dict[f"card{pick}"]
        aa1 = int(self.deck_p1_picked['attack'])
        aa2 = int(self.deck_p1_picked['defense'])
        aa3 = self.deck_p1_picked['element']
        sum1 = aa1 + aa2
        self.lbl_my_result.setText(str(f'Result: {sum1}'))

        # sum of stats p2 fake pick
        print(self.deck_p2_picked)
        self.deck_p2_picked = self.deck_p2_new_dict[f'card{pick}']
        bb1 = int(self.deck_p2_picked['attack'])
        bb2 = int(self.deck_p2_picked['defense'])
        bb3 = self.deck_p2_picked['element']
        sum2 = bb1 + bb2
        print(sum2)

    def start(self, p1, p2):
        # remove arguments
        self.deck_p1 = random.sample(CARD, 5)
        self.deck_p2 = random.sample(CARD, 5)

        """ get all images from folder """
        self.get_all_images()

        # random cards
        random_cards_p1 = random.sample(self.all_cards, 5)

        for i in range(len(random_cards_p1)):
            self.deck_p1_new.append(random_cards_p1[i])
            self.deck_p1_new.append(random_cards_p1[i].split('_'))

        self.convert_filename_to_dict(self.deck_p1_new)

        # generate cards for the opponent
        random_cards_p2 = random.sample(self.all_cards, 5)

        for k in range(len(random_cards_p2)):
            self.deck_p2_new.append(random_cards_p2[k])
            self.deck_p2_new.append(random_cards_p2[k].split('_'))

        self.convert_filename_to_dict(self.deck_p2_new)
        # - -
        self.set_cards_on_deck()

    def match(self):
        # remove cards image from deck
        self.played_cards -= 1
        i = self.played_cards
        self.img_enemy_cards.setPixmap(QtGui.QPixmap(f"./assets/enemy_card{i}.png"))

        # update score style
        self.lbl_score.setStyleSheet(lbl_score)

        # get score from players
        a = self.total_p1
        b = self.total_p2

        # set score in the labels
        self.lbl_enemy_attack.setText(str(f'Attack: {self.en_attack}'))
        self.lbl_enemy_defense.setText(str(f'Defense: {self.en_defense}'))
        self.lbl_enemy_element.setText(str(f'Element: {self.en_element}'))

        # check if someone win
        if a > b:
            self.score_p1 += 1
            self.lbl_score.setText(f'{self.total_p1} x {self.total_p2}')
            self.winner()
        elif b > a:
            self.score_p2 += 1
            self.lbl_score.setText(f'{self.total_p1} x {self.total_p2}')
            self.winner()
        else:
            self.score_p1 += 1
            self.score_p2 += 1
            self.lbl_score.setText(f'{self.total_p1} x {self.total_p2}')
            self.winner()

        # set score
        self.inp_score_p1.setText(str(self.score_p1))
        self.inp_score_p2.setText(str(self.score_p2))

    def winner(self):
        if self.score_p1 == 3 and self.score_p2 == 3:
            self.lbl_score.setStyleSheet(lbl_winner)
            self.lbl_score.setText(f'Draw')
        elif self.score_p2 == 3:
            self.lbl_score.setStyleSheet(lbl_winner)
            self.lbl_score.setText(f'{self.inp_name_p2.text()} won')
        elif self.score_p1 == 3:
            self.lbl_score.setStyleSheet(lbl_winner)
            self.lbl_score.setText(f'{self.inp_name_p1.text()} won')
        else:
            pass

    def reset(self):
        self.score_p1 = 0
        self.score_p2 = 0
        self.inp_score_p1.setText('0')
        self.inp_score_p2.setText('0')
        self.lbl_score.setText('0 x 0')

        self.played_cards = 5
        self.img_enemy_cards.setPixmap(QtGui.QPixmap(f"./assets/enemy_card5.png"))

    def w_options(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Options.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def get_all_images(self):
        # get all images from folder
        self.all_cards = glob.glob('./assets/cards/*.png')

    def set_cards_on_deck(self):
        # update card image on deck

        if bool(self.deck_p1_new_dict):
            i1 = QtGui.QIcon()
            i1.addPixmap(QtGui.QPixmap(self.deck_p1_new_dict[f'card1']['filename']), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.card_1.setIcon(i1)

            i2 = QtGui.QIcon()
            i2.addPixmap(QtGui.QPixmap(self.deck_p1_new_dict[f'card2']['filename']), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
            self.card_2.setIcon(i2)

            i3 = QtGui.QIcon()
            i3.addPixmap(QtGui.QPixmap(self.deck_p1_new_dict[f'card3']['filename']), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
            self.card_3.setIcon(i3)

            i4 = QtGui.QIcon()
            i4.addPixmap(QtGui.QPixmap(self.deck_p1_new_dict[f'card4']['filename']), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
            self.card_4.setIcon(i4)

            i5 = QtGui.QIcon()
            i5.addPixmap(QtGui.QPixmap(self.deck_p1_new_dict[f'card5']['filename']), QtGui.QIcon.Normal,
                         QtGui.QIcon.Off)
            self.card_5.setIcon(i5)
        else:
            print('The deck is empty')

    def convert_filename_to_dict(self, card):
        p1_dict_new = {
            'card1': {
                'attack': card[1][1],
                'defense': card[1][2],
                'element': card[1][3].split('.')[0],
                'filename': card[0]
            },
            'card2': {
                'attack': card[3][1],
                'defense': card[3][2],
                'element': card[3][3].split('.')[0],
                'filename': card[2]
            },
            'card3': {
                'attack': card[5][1],
                'defense': card[5][2],
                'element': card[5][3].split('.')[0],
                'filename': card[4]
            },
            'card4': {
                'attack': card[7][1],
                'defense': card[7][2],
                'element': card[7][3].split('.')[0],
                'filename': card[6]
            },
            'card5': {
                'attack': card[9][1],
                'defense': card[9][2],
                'element': card[9][3].split('.')[0],
                'filename': card[8]
            },
        }
        self.deck_p1_new_dict = p1_dict_new
        #
        p2_dict_new = {
            'card1': {
                'attack': card[1][1],
                'defense': card[1][2],
                'element': card[1][3].split('.')[0],
                'filename': card[0]
            },
            'card2': {
                'attack': card[3][1],
                'defense': card[3][2],
                'element': card[3][3].split('.')[0],
                'filename': card[2]
            },
            'card3': {
                'attack': card[5][1],
                'defense': card[5][2],
                'element': card[5][3].split('.')[0],
                'filename': card[4]
            },
            'card4': {
                'attack': card[7][1],
                'defense': card[7][2],
                'element': card[7][3].split('.')[0],
                'filename': card[6]
            },
            'card5': {
                'attack': card[9][1],
                'defense': card[9][2],
                'element': card[9][3].split('.')[0],
                'filename': card[8]
            },
        }
        self.deck_p2_new_dict = p2_dict_new


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
